import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

const helveticaNeue = localFont({
  src: [
    {
      path: './fonts/HelveticaNeue/HelveticaNeue-01.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/HelveticaNeue/HelveticaNeue-Bold-02.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/HelveticaNeue/HelveticaNeue-Italic-03.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/HelveticaNeue/HelveticaNeue-Medium-11.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/HelveticaNeue/HelveticaNeue-MediumItalic-12.ttf',
      weight: '500',
      style: 'italic',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helveticaNeue.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
