import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';
import Footer from "./components/Footer";
import { ContactQueryResult } from "@/sanity/types";
import { sanityFetch } from "./lib/sanityFetch";
import { contactQuery } from "./lib/queries";
// import NameBanner from "../../public/nameBanner";

const helveticaNeue = localFont({
  src: [
    {
      path: './fonts/HelveticaNeue/HelveticaNeue-01.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/HelveticaNeue/HelveticaNeue-Bold-02.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/HelveticaNeue/HelveticaNeue-Italic-03.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/HelveticaNeue/HelveticaNeue-Medium-11.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/HelveticaNeue/HelveticaNeue-MediumItalic-12.ttf',
      weight: '500',
      style: 'italic',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const contactInfo: ContactQueryResult = await sanityFetch<ContactQueryResult>({
    query: contactQuery,
    tags: ['contact'],
  })

  return (
    <html lang="en">
      <body
        className={`${helveticaNeue.className} antialiased`}
      >
        <div className="min-h-[calc(100vh-133px)]">
          {/* <div className="px-[16px] pt-[16px] md:px-6 md:pt-6 md:w-[50vw] ">
            <NameBanner />
          </div> */}
          {children}
        </div>
        {/* FOOTER */}
        <Footer contactInfo={contactInfo} />
      </body>
    </html>
  );
}
